server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livecommerce?characterEncoding=UTF-8
    username: test
    password: 12345678!
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: test
    password: 12345678!
    url: jdbc:mysql://localhost:3306/livecommerce?characterEncoding=UTF-8
  redis:
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: com.flab.livecommerce.domain
  configuration:
    map-underscore-to-camel-case: true
